version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-ts-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - frontend-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  frontend-network:
    external: true
    name: frontend-network 