version: '3.8'

services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: express-ts-api-dev
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=development
      - PORT=3005
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - web-network

networks:
  web-network:
    # external: true
    name: web-network 
    